### ISSUE TITLE
Uploaded images 404

### ISSUE THREAD

**Issue by cowera** [butaminas/ultimate-forge-deployment-script#1]
This worked just fine:
`ln -nfs ../../"$domain"_uploads ./uploads`

I can `cd` into the upload directory and end up in the linked folder outside of root.

However, even though this worked, I cannot seem to access any images that I have in my `$domain_uploads` folder. When I try to look at one by using a browser I get a 404 error. Any idea why this could be?

**Comment by butaminas** [comment]
@Hillcow have you checked your folder permissions? Perhaps your uploads directory (that is outside of root) doesn't have the right permissions, therefore, you get this error?

I've done this a couple of times already on different projects, so this should work without a problem.
